#!/bin/bash

function print_help_and_exit
{
cat >&2 << 'EOF'

'voropadding' script pads (fills up the space around) the selected part of the input molecule (e.g. a ligand)
and then calculates the total available volume and the total interface area of the padded part.

Options:
    --input                       string  *  input file path for a molecule, must be in PDB or mmCIF format
    --selection                   string     selection of the structural part to pad and analyze, default is '(not [-protein])'
    --max-padding                 number     maximum number of padding layers, default is 2
    --restriction-centers         string     selection of the atoms to be used as centers of the restriction spheres, default is ''
    --restriction-radius          number     radius to be used for the restriction spheres (if any), default is 10.0
    --output-table-file           string     output table file path, default is '_stdout' to print to stdout
    --output-graphics-file        string     output file path for the PyMol drawing script, default is ''
    --graphics-mode               string     graphics output mode, may be 'basic' or 'detailed', default is 'basic'
    --print-mode                  string     printing to stdout mode, can be 'h' or 'v', default is 'h'
    --help | -h                              flag to display help message and exit

Standard output:
    space-separated table of values

Examples:

    voropadding --input "./complex.pdb"

    voropadding --input "./complex.pdb" --selection '[-chain B]' 

    voropadding --input "./complex.pdb" --restriction-centers '[-chain A -rnum 30 -aname CB]' --restriction-radius 12.0

    voropadding --input "./complex.pdb" --max-padding 3 --output-graphics-file "./padded.py"

EOF
exit 1
}

################################################################################

export LANG=C
export LC_ALL=C

SCRIPTDIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

readonly ZEROARG=$0
ALLARGS=("$@")

if [ -z "$1" ]
then
	print_help_and_exit
fi

INPUT_FILE=""
SELECTION="(not [-protein])"
MAX_PADDING="2"
RESTRICTION_CENTERS=""
RESTRICTION_RADIUS="10.0"
OUTPUT_TABLE_FILE="_stdout"
OUTPUT_GRAPHICS_FILE=""
GRAPHICS_MODE="basic"
PRINT_MODE="h"
HELP_MODE="false"

while [[ $# > 0 ]]
do
	OPTION="$1"
	OPTARG="$2"
	shift
	case $OPTION in
	--input)
		INPUT_FILE="$OPTARG"
		shift
		;;
	--selection)
		INPUT_LIGAND="$SELECTION"
		shift
		;;
	--max-padding)
		MAX_PADDING="$OPTARG"
		shift
		;;
	--restriction-centers)
		RESTRICTION_CENTERS="$OPTARG"
		shift
		;;
	--restriction-radius)
		RESTRICTION_RADIUS="$OPTARG"
		shift
		;;
	--output-table-file)
		OUTPUT_TABLE_FILE="$OPTARG"
		shift
		;;
	--output-graphics-file)
		OUTPUT_GRAPHICS_FILE="$OPTARG"
		shift
		;;
	--graphics-mode)
		GRAPHICS_MODE="$OPTARG"
		shift
		;;
	--print-mode)
		PRINT_MODE="$OPTARG"
		shift
		;;
	-h|--help)
		HELP_MODE="true"
		;;
	*)
		echo >&2 "Error: invalid command line option '$OPTION'"
		exit 1
		;;
	esac
done

if [ "$HELP_MODE" == "true" ]
then
	print_help_and_exit
fi

if [ -z "$INPUT_FILE" ]
then
	echo >&2 "Error: no input file provided"
	exit 1
fi

if [ ! -s "$INPUT_FILE" ]
then
	echo >&2 "Error: no input file '$INPUT_FILE'"
	exit 1
fi

if [ -z "$SELECTION" ]
then
	echo >&2 "Error: no selection provided"
	exit 1
fi

if [ -z "$MAX_PADDING" ] || [ "$MAX_PADDING" -lt "1" ] || [ "$MAX_PADDING" -gt "10" ]
then
	echo >&2 "Error: invalid value '$MAX_PADDING' for the maximum number of padding layers, must be an integer between 1 and 10"
	exit 1
fi

if [ "$GRAPHICS_MODE" != "basic" ] && [ "$GRAPHICS_MODE" != "detailed" ]
then
	echo >&2 "Error: invalid graphics mode, must be either 'basic' or 'detailed'"
	exit 1
fi

if [ "$PRINT_MODE" != "h" ] && [ "$PRINT_MODE" != "v" ]
then
	echo >&2 "Error: invalid printing mode '$PRINT_MODE', must be 'h' or 'v'"
	exit 1
fi

GRAPHICS_PARAMETERS_INVDW=""
GRAPHICS_PARAMETERS_INSAS=""
GRAPHICS_PARAMETERS_PADDED=""
if [ -n "$OUTPUT_GRAPHICS_FILE" ]
then
	GRAPHICS_BASENAME="$(basename ${OUTPUT_GRAPHICS_FILE} .py | tr '.' '_')"
	GRAPHICS_PARAMETERS_INVDW="--graphics-output-file ./draw_invdw.py --graphics-title ${GRAPHICS_BASENAME}_vdW --graphics-restrict-representations balls --graphics-restrict-chains ligand --graphics-color-balls 0x00FFFF"
	GRAPHICS_PARAMETERS_INSAS="--graphics-output-file ./draw_insas.py --graphics-title ${GRAPHICS_BASENAME}_in_SAS --graphics-restrict-representations wireframe faces --graphics-restrict-chain-pairs receptor ligand --graphics-color-faces 0x00FF00 --graphics-color-wireframe 0x007777"
	GRAPHICS_PARAMETERS_PADDED="--graphics-output-file ./draw_padded.py --graphics-title ${GRAPHICS_BASENAME}_padded --graphics-restrict-representations wireframe faces --graphics-restrict-chain-pairs receptor ligand cap ligand --graphics-color-faces 0xFFFF00 --graphics-color-wireframe 0x777777"
fi

readonly TMPLDIR=$(mktemp -d)
trap "rm -r $TMPLDIR" EXIT

cat "$INPUT_FILE" > "${TMPLDIR}/rawinput"

cd "$TMPLDIR"

{
cat << EOF
var params={}
params.selection='$SELECTION';
params.restriction_selection='$RESTRICTION_CENTERS';
EOF

cat << 'EOF'
voronota_setup_defaults("-no-load-voromqa-potentials", "-no-load-more-atom-types", "-no-load-mock-voromqa-potential");
EOF

if [[ "$INPUT_FILE" == *.cif ]] || [[ "$INPUT_FILE" == *.CIF ]]
then
cat << 'EOF'
voronota_import_mmcif("-files", ["./rawinput"], "-include-heteroatoms");
voronota_assert_full_success("Failed to input mmCIF file");
EOF
else
cat << 'EOF'
voronota_import("-file", "./rawinput", "-include-heteroatoms");
voronota_assert_full_success("Failed to input PDB file");
EOF
fi

cat << 'EOF'
voronota_delete_tags_of_atoms("-tags", "het");
voronota_export_atoms("-use", "("+params.selection+")", "-file", "ligand.pa");
voronota_assert_full_success("Failed to write selection");
voronota_export_atoms("-use", "(not ("+params.selection+"))", "-file", "receptor.pa");
voronota_assert_full_success("Failed to write selection complementary");
if(params.restriction_selection)
{
	voronota_export_atoms("-use", "("+params.restriction_selection+")", "-file", "restriction.pa");
	voronota_assert_full_success("Failed to write restriction");
}
EOF
} \
| ${SCRIPTDIR}/tools/voronota-js --no-setup-defaults

if [ ! -s "ligand.pa" ]
then
	echo >&2 "Error: failed to select atoms from '${INPUT_FILE}' using selection '${SELECTION}'"
	exit 1
fi

if [ ! -s "receptor.pa" ]
then
	echo >&2 "Error: failed to select atoms from '${INPUT_FILE}' using selection '(not (${SELECTION}))'"
	exit 1
fi

if [ -n "$RESTRICTION_CENTERS" ] && [ ! -s "restriction.pa" ]
then
	echo >&2 "Error: failed to select restriction center atoms from '${INPUT_FILE}' using selection '(not (${RESTRICTION_CENTERS}))'"
	exit 1
fi

{
cat "receptor.pa" | awk '{print "receptor " $2 " " $3 " " $4 " " $5}'
cat "ligand.pa" | awk '{print "ligand " $2 " " $3 " " $4 " " $5}'
} \
> "./inputballs"

cat "./inputballs" \
| ${SCRIPTDIR}/tools/voronota-lt ${GRAPHICS_PARAMETERS_INVDW} \
  --probe 0.001 \
  --print-contacts-chain-level \
  --print-cells-chain-level \
2> /dev/null \
> "./tessellation_summary_invdw"

if [ ! -s "tessellation_summary_invdw" ]
then
	echo >&2 "Error: failed to calculate tessellation summary constrained by the van der Waals surface"
	exit 1
fi

cat "./inputballs" \
| ${SCRIPTDIR}/tools/voronota-lt ${GRAPHICS_PARAMETERS_INSAS} \
  --probe 1.4 \
  --print-contacts-chain-level \
  --print-cells-chain-level \
2> /dev/null \
> "./tessellation_summary_insas"

if [ ! -s "tessellation_summary_insas" ]
then
	echo >&2 "Error: failed to calculate basic tessellation summary constrained by the SAS"
	exit 1
fi

PARAMS_FOR_BOUNDING_SPHERES=""

if [ -s "restriction.pa" ]
then
	cat "restriction.pa" | awk -v radius=${RESTRICTION_RADIUS} '{print $2 " " $3 " " $4 " " radius}' | tr '\n' ' ' > "./restriction_spheres"
	PARAMS_FOR_BOUNDING_SPHERES="--bound-by-spheres $(cat './restriction_spheres')"
fi

cat "./inputballs" \
| ${SCRIPTDIR}/tools/sihsolvexpand ${PARAMS_FOR_BOUNDING_SPHERES} \
  --chain-of-interest "ligand" \
  --max-layers "$MAX_PADDING" \
2> /dev/null \
> "./padded_complex"

if [ ! -s "padded_complex" ]
then
	echo >&2 "Error: failed to generate a padded structure"
	exit 1
fi

cat "./padded_complex" \
| ${SCRIPTDIR}/tools/voronota-lt ${GRAPHICS_PARAMETERS_PADDED} \
  --print-contacts-chain-level \
  --print-cells-chain-level \
2> /dev/null \
> "./tessellation_summary_padded"

if [ ! -s "tessellation_summary_padded" ]
then
	echo >&2 "Error: failed to calculate tessellation summary"
	exit 1
fi

if [ -n "$OUTPUT_GRAPHICS_FILE" ] && [ ! -s "draw_padded.py" ]
then
	echo >&2 "Error: failed to generate graphics"
	exit 1
fi

read LIGAND_AREA_INVDW LIGAND_VOLUME_INVDW LIGAND_ATOMS_COUNT <<< "$(cat ./tessellation_summary_invdw | awk '{if($1=="su" && $2=="ligand"){print $5 " " $6 " " $7}}')"
read LIGAND_AREA_INSAS LIGAND_VOLUME_INSAS <<< "$(cat ./tessellation_summary_insas | awk '{if($1=="su" && $2=="ligand"){print $5 " " $6}}')"
read LIGAND_VOLUME_PADDED <<< "$(cat ./tessellation_summary_padded | awk '{if($1=="su" && $2=="ligand"){print $6}}')"

read LIGAND_IFACE_AREA_INSAS LIGAND_IFACE_BOUNDARY_INSAS <<< "$(cat ./tessellation_summary_insas | awk '{if($1=="cu" && (($2=="ligand" && $5=="receptor") || ($2=="receptor" && $5=="ligand"))){print $8 " " $9}}')"
read LIGAND_IFACE_AREA_PADDED LIGAND_IFACE_BOUNDARY_PADDED <<< "$(cat ./tessellation_summary_padded | awk '{if($1=="cu" && (($2=="ligand" && $5=="receptor") || ($2=="receptor" && $5=="ligand"))){print $8 " " $9}}')"

VOLUME_FREEDOM_COEF="$(echo ${LIGAND_VOLUME_PADDED} ${LIGAND_VOLUME_INVDW} | awk '{print ($1/$2)}')"
IFACE_FREEDOM_COEF="$(echo ${LIGAND_IFACE_AREA_PADDED} ${LIGAND_IFACE_AREA_INSAS} | awk '{print ($1/$2)}')"

{
echo "input  volume_freedom_coef  interface_freedom_coef  volume_padded  iface_area_padded  iface_boundary_padded  volume_unpadded  iface_area_unpadded  iface_boundary_unpadded  sasa_unpadded  volume_vdw  atoms_count  max_padding"
echo "$(basename ${INPUT_FILE})  $VOLUME_FREEDOM_COEF  $IFACE_FREEDOM_COEF  $LIGAND_VOLUME_PADDED  $LIGAND_IFACE_AREA_PADDED  $LIGAND_IFACE_BOUNDARY_PADDED  $LIGAND_VOLUME_INSAS  $LIGAND_IFACE_AREA_INSAS  $LIGAND_IFACE_BOUNDARY_INSAS  $LIGAND_AREA_INSAS  $LIGAND_VOLUME_INVDW  $LIGAND_ATOMS_COUNT  $MAX_PADDING"
} \
| column -t \
> "./final_result.txt"

cd - &> /dev/null

if [ -n "$OUTPUT_TABLE_FILE" ] && [ "$OUTPUT_TABLE_FILE" != "_stdout" ]
then
	mkdir -p "$(dirname ${OUTPUT_TABLE_FILE})"
	cat "${TMPLDIR}/final_result.txt" > "$OUTPUT_TABLE_FILE"
else
	if [ "$PRINT_MODE" == "v" ]
	then
		paste \
		  <(cat "${TMPLDIR}/final_result.txt" | head -1 | sed 's/\s\+/\n/g') \
		  <(cat "${TMPLDIR}/final_result.txt" | tail -1 | sed 's/\s\+/\n/g') \
		| column -t
	else
		cat "${TMPLDIR}/final_result.txt"
	fi
fi

if [ -n "$OUTPUT_GRAPHICS_FILE" ]
then
	mkdir -p "$(dirname ${OUTPUT_GRAPHICS_FILE})"
	
	{
		if [ "$GRAPHICS_MODE" == "detailed" ]
		then
			cat "${TMPLDIR}/draw_invdw.py" "${TMPLDIR}/draw_insas.py" "${TMPLDIR}/draw_padded.py"
		else
			cat "${TMPLDIR}/draw_invdw.py" "${TMPLDIR}/draw_padded.py"
		fi
	} \
	| egrep -v '^cmd\.load_cgo\(cgo_graphics_list_faces_contacts_cap_ligand' \
	> "$OUTPUT_GRAPHICS_FILE"
fi

